eureka:
  instance:
    hostname: localhost
    port: 9001
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 9100
spring:
  application:
    name: eureka-client-1